### ISSUE TITLE
[QUESTION] How to replace column values in dataframe-js?

### ISSUE THREAD

**Issue by tony-bony** [Gmousse/dataframe-js#100]
**Question**
I have recently posted [this question](https://stackoverflow.com/questions/58781905/how-to-replace-column-values-in-dataframe-js/58782807#58782807) on stackoverflow
Could you please confirm this is the right way to do it?

I was thinking there would be an easy way to do it, like: `df1['c2'] = df2.toArray('c2')` ?

**Context**
I am using dataframe-js in JS callback in [Bokeh](https://docs.bokeh.org/en/1.4.0/)

**Comment by Gmousse** [comment]
Hi @tony-bony, sorry for the delay, I wasn't active these days.

The dataframe-js DataFrame is not subscriptable (like pandas). It uses an api similar to Spark, with functionnal programming patterns.

But it's a limitation, I will add an easier way for people coming from pandas and other languages.
