### ISSUE TITLE
[BUG] The GroupedDataFrame documentation bug

### ISSUE THREAD

**Issue by Gmousse** [Gmousse/dataframe-js#101]
**Describe the bug**
The GroupedDataFrame documentation isn't visible.

**To Reproduce**
Go to https://gmousse.gitbooks.io/dataframe-js/content/doc/api/groupedDataframe.html

**Expected behavior**
It should work.

**Comment by yehosef** [comment]
it's over here 
 https://github.com/Gmousse/dataframe-js/blob/feature/column/doc/api/groupedDataframe.md
It'd be great if it was in the gitdoc
