### ISSUE TITLE
[BUG] Minor documentation issues for API references

### ISSUE THREAD

**Issue by dhorvay** [Gmousse/dataframe-js#104]
**Describe the bug**
The API references in documentation are pointing to wrong hyperlink, which results in error to see exact lines of code that is referred.

**To Reproduce**
1. Go to [https://gmousse.gitbooks.io/dataframe-js/content/doc/api/dataframe.html#dataframe](https://gmousse.gitbooks.io/dataframe-js/content/doc/api/dataframe.html#dataframe)
2. Click on [src/dataframe.js:11-1243](https://github.com/:Gmousse/dataframe-js/blob/ec685babaf21f5c5c74b51405f3b5344642b8849/src/dataframe.js#L11-L1243)
3. See error e.g. error: "Not Found" (Firefox)

**Expected behavior**
I expect that the link will go directly to the line of code being referred

**Screenshots**
<img width="432" alt="Screen Shot 2020-04-05 at 11 00 28 PM" src="https://user-images.githubusercontent.com/18173173/78519431-51873480-7791-11ea-9af0-afe63da90906.png">

**Desktop:**
 - OS: macOS Catalina 10.15.3
 - Browser: Mozilla Firefox 74.0
 - Version: dataframe-js 1.4.3

**Additional context**
Issue is unneeded colon.

**Comment by dhorvay** [comment]
Easy fix. Will make PR when #101 is closed.

**Comment by Gmousse** [comment]
Thank you @dhorvay  ! 
Your PR is welcome (#101 is closed on develop).

**Comment by Gmousse** [comment]
@dhorvay The error seems related to the library used to build the documentation https://github.com/documentationjs/documentation/issues/1295

I will update it and publish it on the hotfix 1.4.4 (no need of a PR here)

Thanks !
