### ISSUE TITLE
[BUG] Typo in the documentation

### ISSUE THREAD

**Issue by ThatIsAPseudo** [Gmousse/dataframe-js#113]
**Describe the bug**
I think there is a typo in the docs, where `dim` is described.
Isn't it "width" ("largeur" in French) instead of "weight" ("poids" in French) ?

> ## dim
> src/dataframe.js:481-483
>
> Get the DataFrame dimensions.
>
> **Examples**
>```javascript
>const [height, weight] = df.dim()
>```
>Returns Array The DataFrame dimensions. [height, weight]

**To Reproduce**
Go to https://gmousse.gitbooks.io/dataframe-js/content/doc/api/dataframe.html#dim

**Comment by Gmousse** [comment]
Hi ! 

Thanks for the report.

It's fixed in 1.4.4
