### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by DeliciousPickle** [Gmousse/dataframe-js#13]
In the API documentation, the example you give for groupBy is this:

> groupedDF.aggregate(group => group.sql.sum('column1'));

When I try to do this it throws the error: "Uncaught (in promise) TypeError: group.sql.sum is not a function(...)".

I experimented with using "group.**stat**.sum" instead, and that seems to work.

It could be that your documentation is wrong, and you need to change _group.sql.sum_ to _group.stat.sum_.  Or is it the case that I should actually use _group.sql.sum_ and I'm lacking something that will bring the _group.sql.sum_ function into scope?

**Comment by Gmousse** [comment]
Hey @DeliciousPickle, you are right, it's a documentation error.
As you expected you have to use the `.sum()` method from the Stat module, not SQL. My bad ^^.
I will fix the doc right now. 
Thx

**Comment by Gmousse** [comment]
Ok, I have updated the documentation (web and markdown).
Thanks @DeliciousPickle !
