### ISSUE TITLE
Get Row by index  

### ISSUE THREAD

**Issue by hainessss** [Gmousse/dataframe-js#22]
How would you get a row by its index, or perform an action on an individual row?  Only way i can see is give a row an ID and filter by it then map over it.

**Comment by Gmousse** [comment]
Hi @hainessss .
for now the DataFrame hasn't good ways to modify only one row (I work on a new version where rows have index).

If you want to modify rows one by one, it's maybe better to switch on array (toArray, toCollection) and then work by reference (which isn't possible with the dataframe-js).

To select only one row you can also use the .find method.
To modify only one row you can use the .map with a ternary condition. e.g. df.map(row => row.get("myindex") === 3 ? row.set("whatever", "whatever") : row)

I will take your request in account on the new version.

**Comment by hainessss** [comment]
Yes, thank you, @Gmousse. That api looks good.

**Comment by Gmousse** [comment]
Resolved, merged on develop. Will be releases as 1.4.0.
