### ISSUE TITLE
Sort-by multiple columns

### ISSUE THREAD

**Issue by Jefftopia** [Gmousse/dataframe-js#29]
SortBy should take in multiple columns, ordered left to right by decreasing "priority". When a column to the left has the same value, the column to the right should tie-break it. 

I hope to have time to investigate and create a PR for this soon. If you already have an implementation in mind, so much the better!

Example: `myDf.sortBy('Test A Score', 'Test B Score', 'Test C Score');`

| Student | Test A Score | Test B Score | Test C Score |
|----------|--------------|--------------|--------------|
| Henry | 95 | 90 | 76 |
| Jess | 95 | 90 | 75 |
| William | 95 | 89 | 76 |
| Clair | 95 | 89 | 76 |
| Barbara | 94 | 99 | 99 |
| John | 94 | 98 | 77 |
----------------------

**Comment by Gmousse** [comment]
Hey, really interesting. I want to see this :D

**Comment by Jefftopia** [comment]
@Gmousse Yes, I have a working version locally, just need to add test coverage...stay tuned.
