### ISSUE TITLE
.listColumns() does not contain columns added with row.set()

### ISSUE THREAD

**Issue by martinv13** [Gmousse/dataframe-js#30]
Hello,
It could be useful if `.listColumns()` were updated to give the actual columns names, including those added with `.map(row => row.set("test",1))` for instance (I would like to use it with dynamic columns names not known in advance). 
Instead, it gives only the columns names given to the constructor.
A quick and dirty fix is to convert the DF to collection and  back to DF, but it is not really satisfactory.
I am not sure of what would be the most efficient way to do it but I can try and fill a PR if I find something.
This is a very useful package btw, thank you @Gmousse!
Martin

**Comment by Gmousse** [comment]
hi @martinv13 
I have an idea for a quick fix. I will see tonight.

**Comment by Gmousse** [comment]
@martinv13 I have created a simple fix.
I will try to increase performances and schema check in few days in a next feature.

Can you validate the PR #31 (by pulling and testing the branch or by looking at unit tests) ?
Anyways I will publish this hotfix tomorrow in 1.2.7.

**Comment by Gmousse** [comment]
However it's now also work with Row.delete.

**Comment by martinv13** [comment]
Hi @Gmousse,
Sorry for the delay
PR #31 works perfectly as you described it and does the job
Thanks!

**Comment by Gmousse** [comment]
ok I will publish it today.
Thank you for the test and the issue.

**Comment by Gmousse** [comment]
PR merged and released in 1.2.7
