### ISSUE TITLE
Aggregate multiple columns at once using reduce and aggregate in GroupedDataFrame 

### ISSUE THREAD

**Issue by kushukla** [Gmousse/dataframe-js#33]
While having multiple values returned from reduce function is very straight forward. Like:

```javascript
// df being Titanic.csv
    df.reduce((p, n) => (
      { sum: +n.get('Freq') + p.sum, 
        max: +n.get('Freq') > p.max ? +n.get('Freq') : p.max   
      }), 
      {sum: 0, max: -999}   
    ).show();
```
Output:
```
{sum: 2201, max: 670}
```

If I try to use similar reduce function on GroupedDataFrame like below:

```javascript
df.groupBy('Class').aggregate(group => group.reduce((p, n) =>
      ({  sum: +n.get('Freq') + p.sum,
          max: +n.get('Freq') > p.max ? +n.get('Freq') : p.max
        }),
        {sum: 0, max: -999}   )
    , 'new col').show();
```

As expected the output is a JSON object stored in a column, which can further be mapped into separate columns. 
```
| Class     | new col   |
------------------------
| 1st       | [objec... |
| 2nd       | [objec... |
| 3rd       | [objec... |
| Crew      | [objec... |
```
However it would be better if each of the variables in JSON can be expanded as a separate columns like below:

```
| Class     | sum       | max       |
-----------------------------------
| 1st       | 325       | 140       |
| 2nd       | 285       | 154       |
| 3rd       | 706       | 387       |
| Crew      | 885       | 670       |
```
Is there a way to achieve similar result in dataframe-js? Such feature is available in R's data.table package, great to have similar in dataframe-JS too.

Thanks!
Kunal

**Comment by Gmousse** [comment]
Hi @kushukla,
It could be a good idea to implement an aggregation generating multiple columns (instead of one).
I will see how add this feature without breaking things.

Waiting this release you can already do that (in a non-user-friendly way) like that:

With dataframe-js >= 1.2.7 :
````js
var testDF = new DataFrame(dat);
testDF.groupBy("type")
    .aggregate(gdf => ({meanScore: gdf.stat.mean('score'), stdevScore: gdf.stat.stdev('score')}), 'stats')
    .map(row => {
         return row.set('meanScore', row.get('stats').meanScore)
                         .set('stdevScore', row.get('stats').stdevScore)
     })
````

With dataframe-js > 1.2.7 :
````js
testDF.groupBy("type")
    .aggregate(gdf => ({meanScore: gdf.stat.mean('score'), stdevScore: gdf.stat.stdev('score')}), 'stats')
    .withColumn('meanScore', row => row.get('stats').meanScore)
    .withColumn('maxScore', row => row.get('stats').maxScore);
````

Stay tuned about this new feature :D.

**Comment by kushukla** [comment]
Thanks! @Gmousse, this is perfect. Looking forward to new features :)
