### ISSUE TITLE
Any plan on supporting TypeScript with a Definitions.ts file?

### ISSUE THREAD

**Issue by willkara** [Gmousse/dataframe-js#43]
Trying to use it in my AngularCLI project with TypeScript.

I tried importing with yarn and even adding the CDN version but it's either asking for the types or not working at all. Maybe a types file can be created for https://github.com/DefinitelyTyped/DefinitelyTyped

Perhaps there is another way to import it?

Would love it if someone could point me in the right direction :)

**Comment by Gmousse** [comment]
Hi @willkara,

I haven't knowledges about typescript (and how a js module can be used on it).

I will do some researches and tell some friends.

If a configuration file is required, i will create a pull request. Stay tuned

**Comment by Gmousse** [comment]
@willkara I have created a dts file (using dts-gen).
It seems to work.

Can you try to install the PR branch using npm or yarn (example: `npm install git+https://github.com/Gmousse/dataframe-js.git#feature/support-typescript`) and test it ?

If it works I will merge (and it will be in the incoming release).
Thanks !

**Comment by willkara** [comment]
@Gmousse Thanks for being so receptive! I'll give it a shot once I get home :)

**Comment by willkara** [comment]
Still trying to get it to work correctly but haven't had enough time to really put some decent time into it.

Also, you might want to look into [DefinitleyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) until you can think of making it es2016 compatible with modules.

Just as an FYI, I tried using it outside of this project and it's working amazingly well! :)

Thanks!

**Comment by willkara** [comment]
I can confirm it works!

**Comment by danielgwilson** [comment]
Any plans to get this into DefinitelyTyped?

**Comment by Gmousse** [comment]
Hi @danielgwilson,

Sadly I haven't use TypeScript and I don't know its stack or

**Comment by Gmousse** [comment]
closed in favor of #73
