### ISSUE TITLE
how to add a new module while keeping the existing default module ?

### ISSUE THREAD

**Issue by marvinwu** [Gmousse/dataframe-js#47]
Thanks for this excellent repo,

I am trying to add a new module, and want to keep the existing default modules.

I know we can do this by reimporting the defaults: 
DataFrame.setDefaultModules(SQL, Stat, FakeModule)

but seems the Stat ,SQL and matrix module is not exported, how can I get them and reimport it when setting the default module ?

**Comment by Gmousse** [comment]
Hi, @marvinwu 

If I have well understood, you have two solutions:
- You want to add a module to the default modules (and keep other default modules):

````js
DataFrame.setDefaultModules(...DataFrame.defaultModules, yourModule);
````

- You want to add a module to the current DataFrame instance (or to its copies) and you want to keep default modules:

````js
var df = new DataFrame(yourdata, yourModule);
````

But this way will be deprecated in the next version (>= 1.3.0) by introducing the `options` parameter:

````js
var df = new DataFrame(yourdata, {modules: [yourModule]});
````

**Comment by marvinwu** [comment]
Hi, @Gmousse 

         Thanks much for the speedy reply  ! Thats **exactly** what we are trying to do, I tried out the setDefaultModules syntax and It work perfectly, looking forward to the next release
