### ISSUE TITLE
DataFrame.groupBy slow when the number of groups is high

### ISSUE THREAD

**Issue by rjrivero** [Gmousse/dataframe-js#48]
Thanks for such an useful library. I am using it to process DataFrames over 150 thousand rows and 10 thousand groups, and I am having performance problems with the current implementation of groupBy.

I am sending a Pull request that changes the GroupedDataFrame._groupBy function to loop over the source DataFrame just once, instead of once per group. This change makes my jobs complete in seconds instead of minutes. The PR passes the tests and lint, I hope it is worth including upstream.

**Comment by Gmousse** [comment]
Hi @rjrivero,

Indeed dataframe-js has some methods badly optimized. 


Thanks for this wonderful pr, I will look to do the review tommorrow (I was in business travel). 

I can integrate your pr (if valid) in the next release.

**Comment by Gmousse** [comment]
Thank you ! 
This will be published with other PR this night.

**Comment by rjrivero** [comment]
Glad to be helpful. The new implementation of _groupBy slows down my jobs again, I think the spread operator "...groups" called on each step of the "reduce" function makes the operation roughly O(N*N/2). I will be pushing a new PR to make it O(N) again.
