### ISSUE TITLE
When dataframe.count()===1 shuffle returns empty dataframe.

### ISSUE THREAD

**Issue by fingul** [Gmousse/dataframe-js#53]
When dataframe.count()===1 shuffle returns empty dataframe.

**Comment by Gmousse** [comment]
Indeed this case isn't handled correctly.
I will prepare a fix.

**Comment by Gmousse** [comment]
It was fixed on this PR but I will continue to .reduce issues with empty DataFrame or with DataFrame having only one element.

I hope a release for this hotfix on monday.
