### ISSUE TITLE
Result f sql is always getting undefined

### ISSUE THREAD

**Issue by ollita7** [Gmousse/dataframe-js#59]
Hi, I tried to query using sql but the result is always undefined.

`
var DataFrame = require('dataframe-js').DataFrame;
const df = new DataFrame(pls, columns);
df.sql.register('tmp2', true);
const test = DataFrame.sql.request("SELECT * FROM tmp2");
`

**Comment by Gmousse** [comment]
Hi,
thank you for the report @ollita7 
I will investigate.

The sql part of dataframe-js is a bit experimental, I will see why it returns nothing.

**Comment by ollita7** [comment]
Thanks! 
Let me know if I can help you with something.

**Comment by Gmousse** [comment]
hi @ollita7 
I have tried just a simple code:

````js
const DataFrame = require("dataframe-js").DataFrame;

const fakeData = [{ x: 1, y: 2 }, { x: 2, y: 3 }];

const df = new DataFrame(fakeData);
df.sql.register("tmp2", true);
const test = DataFrame.sql.request("SELECT * FROM tmp2");
test.show();
````

And it works.

Can you give me your nodejs and dataframe version ?

**Comment by ollita7** [comment]
Thanks @Gmousse.
I tried again and it is working
