### ISSUE TITLE
Use columns with different names on join

### ISSUE THREAD

**Issue by ollita7** [Gmousse/dataframe-js#60]
Im trying to use join and i want to specify the columns that i want to join between dfs.

`df.join(df2, 'column1', 'full')`

I asume if i do the following join that column1 name exist in both dfs rigth?
Is it posible to join specifing the columns foreach dfs?

For example I want to join df with df2 on df.column1 = df.column3

Thanks!

**Comment by Gmousse** [comment]
Hi @ollita7,
Indeed it s not possible right now.
I will add this in improvments.

However you can use `withdf.rename(youroldcolumn, yourjoincolumn) ` awaiting a next release.

**Comment by Gmousse** [comment]
Closed due to inactivity
