### ISSUE TITLE
Simplest way to select a column as array?

### ISSUE THREAD

**Issue by pSnehanshu** [Gmousse/dataframe-js#65]

**Comment by Gmousse** [comment]
Hi @pSnehanshu,

Sorry to be late.

I think you can use `yourdf.toArray("yourColumn)`.

Example from the tests:

```js
    assert.deepEqual(
        df.distinct("c1").toArray("c1"),
        [1, 6],
        "distinct, giving a column of unique values."
);
```

Tell me if it's what you need.

**Comment by pSnehanshu** [comment]
@Gmousse `yourdf.toArray("yourColumn")` doesn't work. I have discovered  that `yourdf.getSeries("yourColumn").toArray()` works.

**Comment by Gmousse** [comment]
@pSnehanshu can you give me your dataframe-js version ?

Are you sure you are using dataframe-js and not data-forge ? (getSeries is not a dataframe-js method)

**Comment by pSnehanshu** [comment]
@Gmousse Oops! I'm actually using data-forge. Sorry for the confusion.
The thing is that I initially tried using dataframe-js, but because I couldn't figure out how to do this, I switched to data-forge. This issue was posted before I tried out data-forge.
