### ISSUE TITLE
how to delete rows from a dataframe

### ISSUE THREAD

**Issue by udos** [Gmousse/dataframe-js#67]
let's say there is the following dataframe

```javascript
df = new DataFrame([
  {periodtype: "week", period: null, area: "DE", block: null, source: null},
  {periodtype: "week", period: "front", area: "DE", block: "BS", source: "BEST"},
  {periodtype: "month", period: "front", area: "DE", block: "BS", source: "BEST"}
])
```
at some point I would like to remove the following row:
```javascript
  {periodtype: "week", period: "front", area: "DE", block: "BS", source: "BEST"}
```
I hoped something like the following would do it:
```javascript
df.chain(row=>row.delete({periodtype: "week", period: "front"}))
```
unfortunately not :|

I have the feeling that I am definitely missing something :|

can you point me into the right direction?

**Comment by udos** [comment]
thanks for the super quick response! very clear :)

unfortuantely

```javascript
df.filter(row => row.get("periodtype") !== "week" && row.get("period") !== "front")
```
returns an empty df :| -> sure this is correct?

**Comment by Gmousse** [comment]
Sorry my predicate was bad :D (I didn't read your need correctly).

That's the good one:

```js
df.filter(row => !(row.get("periodtype") === "week" && row.get("period") === "front"))
```

Here you need to drop all rows having periodtype to week and period to front.
(My first version drop all rows having periodtype to week and / or period to front).

Sorry :D

**Comment by udos** [comment]
:) no worries! thanks!
ps: with this, consider to change the question difficulty tag to "difficulty: medium", which does not make me look so bad ;)
