### ISSUE TITLE
It is possible to do a .head or .tail as in pandas?

### ISSUE THREAD

**Issue by jesuskata** [Gmousse/dataframe-js#69]
I am trying do the .head from Pandas, this is the documentation about this:

> `DataFrame.head(n=5)`
> Return the first n rows.
> This function returns the first n rows for the object based on position. It is useful for quickly testing if your object has the right type of data in it.

But I can't find a way to perform this with the `dataframe-js`, BTW an amazing library. We are working with this on an ML project.

**Comment by jesuskata** [comment]
Thanks for your reply:

I did this to solve my problem on the head conversion (maybe it is a little inneficient):

```
const headOmYear = df.toArray().slice(0, topN);
omYear = new DataFrame(headOmYear, df.listColumns());
```

I am receiving a dynamic value (_topN_) to change the size of the dataframe (this was sort by one of four options of columns)

**Comment by Gmousse** [comment]
@jesuskata Feal free to test https://github.com/Gmousse/dataframe-js/tree/feature/sliced-df

It includes, slice, head and tail on the dataframe.

I will add more tests and include it in a new release.

**Comment by jesuskata** [comment]
Awesome!,

Thanks for your great work!
