### ISSUE TITLE
NPM scripts don't work on windows os

### ISSUE THREAD

**Issue by mbkupfer** [Gmousse/dataframe-js#82]
**Describe the bug**
NPM scripts are not compatible on a windows scripts for two reasons:
1. Use of single quotes
2. Setting of environment variables

These have both been mitigated in my PR that I will submit. That said, I'm not sure if this is a complete fix as `npm run test` keeps failing due to an error with XMLHttpRequest regarding the tests involving `DataFrame.fromXXXX`. The error I get is below. 

At the same time, I feel that this might not be related to the issue at hand, because when I remove the offending lines, the tests (and all other scripts) work just fine. This might just be an issue with my machine. Let me know your thoughts. 

```
Unhandled rejection in tests\dataframeIO.test.js

C:\Users\mkupfer\dataframe-js\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:299

Error: Protocol not supported.
```

**Desktop (please complete the following information):**
 - OS: Windows 7 Professional

**Comment by mbkupfer** [comment]
#83

**Comment by mbkupfer** [comment]
#83

**Comment by Gmousse** [comment]
@mbkupfer That's a good point !

**Comment by mbkupfer** [comment]
Also just noticed that `rm` and `mkdir` is not supported on windows. There are a couple solutions out there: I found that [shx](https://www.npmjs.com/package/shx) works fine.

**Comment by mbkupfer** [comment]
@Gmousse I figured out the final piece to the puzzle! The reason that the XMLHttpRequest error was because the protocol `file://` was not being added for windows paths. Adding the `path.startsWith("C")` to file protocol will finally put this issue to rest :raised_hands:

**Comment by Gmousse** [comment]
Your PR #83  is now merged on develop.

It will be included in the next release.
