### ISSUE TITLE
[BUG] The documentation is wrong about toJSON first parameter

### ISSUE THREAD

**Issue by ultimumdesign** [Gmousse/dataframe-js#84]
**Describe the bug**
Thank you for your work. This issue is primarily to thank you, but there is one tiny tiny issue at 
the toJSON function: 
src/dataframe.js:505-513

The inline and official documentation states: @param asCollection default = true
but..
on the function definition it is set to false?

Cheers!

**Comment by Gmousse** [comment]
Hi @ultimumdesign,

Thank you for your question.

Indeed, that's strange, the documentation is wrong about this default parameter which is = to false for now.

I will find when the regression occured and I will fix it in the next patch.

**Comment by Gmousse** [comment]
I couldn't find the regression, I guess this documentation error exists since the begin.

**Comment by Gmousse** [comment]
Pushed on develop. It will released soon.
