### ISSUE TITLE
[FEATURE] group by arbitrary function

### ISSUE THREAD

**Issue by marcosfede** [Gmousse/dataframe-js#85]
**Is your feature request related to a problem? Please describe.**
Can't group by a custom function

**Describe the solution you'd like**
let me pass a function that takes the a row as input and outputs a custom value to group by
eg: `df.groupBy(row => row.name + row.lastname)`

**Comment by Gmousse** [comment]
Hi @marcosfede,
That's a good idea (and it could be extended to the join function).
I will add it in the roadmap.

**Comment by Gmousse** [comment]
After investigating the issue, I don't think that's a good idea in term of data integrity.

**Comment by Gmousse** [comment]
Closed due to inactivity. We will repoen it if necessary.
