### ISSUE TITLE
[QUESTION] Advanced SQL Queries

### ISSUE THREAD

**Issue by MythlinMasterdo** [Gmousse/dataframe-js#89]
**Ask your question**
I am attempting to run a SQL query like this:

`DataFrame.sql.request(SELECT column1, sum(column2) FROM tmp)`

and I get the error: 
`Uncaught NoSuchColumnError: sum(column2) not found in [column1, column2, column3].`

**Additional context**
Other SQL queries work but anything with operators like SUM or GROUP BY throw this no such column error, am I doing this wrong or is there a bug in the library?

**Comment by Gmousse** [comment]
Hi #MythlinMasterdo !

It seems to be a bug. 

Indeed, the SQL module is deprecated (I must add warnings in the next release).
I don't have the time to maintain both the core and this part.

I will have a look to solve it, but please consider using the main JS API.

Stay tuned

**Comment by MythlinMasterdo** [comment]
Thank you @Gmousse depending on my free time I may look into it and open a PR.

**Comment by Gmousse** [comment]
Closed due to inactivity. We will repoen it if necessary.
